"""
Steering behavior and side-effect scoring for Llama-3.2-3B.

Reads samples-llama3b.json (generated by apply_steering.py), scores each
(concept, alpha) combination on:
  - target_score    : keyword hit-rate in generated completions (no model needed)
  - side_effect_ppl : perplexity on math/reasoning probes under steered model
  - fluency_ppl     : perplexity on neutral sentences under steered model

Output: data/steering/scores-llama3b.json
"""

import json
import math
import time
import re
import numpy as np
from pathlib import Path

import mlx.core as mx
from mlx_lm import load
from mlx_lm.models.llama import create_attention_mask

MODEL_ID   = "mlx-community/Llama-3.2-3B-bf16"
VECTORS_PATH = Path(__file__).parent / "vectors-llama3b.json"
SAMPLES_PATH = Path(__file__).parent / "samples-llama3b.json"
OUT_PATH   = Path(__file__).parent / "scores-llama3b.json"

# ── Keyword sets for target-behavior scoring ──────────────────────────────────

TARGET_KEYWORDS = {
    "positive_sentiment": [
        "great", "wonderful", "amazing", "excellent", "fantastic",
        "perfect", "beautiful", "lovely", "incredible", "outstanding",
        "happy", "joyful", "delightful", "splendid", "superb",
        "love", "joy", "best", "awesome", "brilliant",
    ],
    "negative_sentiment": [
        "terrible", "awful", "horrible", "dreadful", "atrocious",
        "disappointing", "frustrating", "miserable", "disgusting", "appalling",
        "bad", "poor", "worst", "pathetic", "ugly",
        "hate", "fear", "pain", "suffering", "failure",
    ],
    "french_language": [
        "vous", "nous", "est", "très", "bien", "que", "pas",
        "qui", "pour", "avec", "bonjour", "merci", "oui", "non",
        "je", "la", "le", "les", "une", "dans",
    ],
    "python_coding": [
        "def ", "import ", "class ", "return ", "print(",
        "if ", "for ", "while ", "try:", "lambda",
        "```python", "numpy", "torch", ".append(", "isinstance(",
        "True", "False", "None", "self.", "elif ",
    ],
    "refusal_behavior": [
        "cannot", "can't", "unable", "decline", "sorry",
        "apologize", "refuse", "won't", "inappropriate", "harmful",
        "outside", "guidelines", "policy", "safety", "ethical",
        "I'm not", "I am not", "I will not", "I cannot", "I can't",
    ],
}

# ── Math / reasoning probes for side-effect scoring ──────────────────────────

MATH_PROBES = [
    "What is 12 plus 15? The answer is 27.",
    "If there are 8 apples and you eat 3, you have 5 left.",
    "A rectangle with width 4 and height 6 has area 24.",
    "7 times 8 equals 56.",
    "The square root of 144 is 12.",
    "If all birds have wings and a robin is a bird, then a robin has wings.",
    "100 divided by 4 equals 25.",
    "2 plus 2 equals 4, and 3 plus 3 equals 6.",
    "If today is Monday, then tomorrow is Tuesday.",
    "A triangle has 3 sides and its angles sum to 180 degrees.",
]

# ── Neutral fluency sentences ─────────────────────────────────────────────────

FLUENCY_SENTENCES = [
    "The sun rises in the east and sets in the west every day.",
    "She walked to the store to buy some bread and milk.",
    "The weather forecast predicts rain for most of the afternoon.",
    "He opened the book and began reading the first chapter slowly.",
    "The children played outside in the park until evening came.",
    "Scientists study the natural world to understand how things work.",
    "The train arrived at the station exactly on schedule this morning.",
    "She prepared a simple meal of pasta with vegetables and sauce.",
    "The library was quiet except for the soft sound of turning pages.",
    "He sent an email to his colleague about the meeting tomorrow.",
]


# ── Steering layer wrapper (same pattern as apply_steering.py) ────────────────

class _SteeringLayer:
    """Wraps a transformer layer, adding alpha × steering_vec to its output."""

    def __init__(self, layer, vecs_mx, alpha):
        self._layer = layer
        self._vecs  = vecs_mx
        self._alpha = float(alpha)

    def __call__(self, x, mask=None, cache=None):
        h = self._layer(x, mask, cache=cache)
        if self._alpha != 0.0:
            for vec in self._vecs:
                h = h + self._alpha * vec.astype(h.dtype)
        return h

    def __getattr__(self, name):
        return getattr(self._layer, name)


def _patch(llama_model, layer_to_vecs, alpha):
    originals = {}
    for idx, vecs in layer_to_vecs.items():
        originals[idx] = llama_model.layers[idx]
        llama_model.layers[idx] = _SteeringLayer(
            llama_model.layers[idx], vecs, alpha
        )
    return originals


def _restore(llama_model, originals):
    for idx, orig in originals.items():
        llama_model.layers[idx] = orig


# ── Scoring helpers ───────────────────────────────────────────────────────────

def keyword_score(text: str, keywords: list[str]) -> float:
    """Return 1.0 if any keyword appears in text (case-insensitive), else 0.0."""
    lo = text.lower()
    return 1.0 if any(kw.lower() in lo for kw in keywords) else 0.0


def keyword_density(text: str, keywords: list[str]) -> float:
    """Keyword occurrences per 100 words."""
    words = text.split()
    if not words:
        return 0.0
    lo = text.lower()
    hits = sum(lo.count(kw.lower()) for kw in keywords)
    return hits / len(words) * 100


def compute_perplexity(
    sentences: list[str],
    model,
    tokenizer,
) -> float:
    """
    Average per-token PPL on `sentences` under the current model state.
    Uses model() directly so any patched _SteeringLayer wrappers are active.
    Avoids materialising the full [T, vocab] log-prob matrix by computing
    log_z (logsumexp) and gathering target-token logits separately.
    """
    total_nll  = 0.0
    total_toks = 0

    for sent in sentences:
        ids = tokenizer.encode(sent, add_special_tokens=True)
        if len(ids) < 2:
            continue
        inp = mx.array([ids])
        logits = model(inp)  # [1, seq_len, vocab]
        T = len(ids) - 1
        targets  = mx.array(ids[1:])
        lgt      = logits[0, :-1, :]             # [T, vocab]
        log_z    = mx.logsumexp(lgt, axis=-1)    # [T]
        target_l = lgt[mx.arange(T), targets]    # [T]
        nlls = (log_z - target_l).astype(mx.float32)
        mx.eval(nlls)
        vals = np.clip(np.array(nlls), 0, 100)
        total_nll  += float(vals.sum())
        total_toks += T

    if total_toks == 0:
        return float("inf")
    return float(math.exp(total_nll / total_toks))


# ── Main ──────────────────────────────────────────────────────────────────────

def main():
    if not SAMPLES_PATH.exists():
        raise FileNotFoundError(
            f"{SAMPLES_PATH} not found — wait for apply_steering.py to finish"
        )

    print(f"Loading samples from {SAMPLES_PATH} ...")
    samples_data = json.loads(SAMPLES_PATH.read_text())
    concepts = list(samples_data["results"].keys())
    alphas   = samples_data["alphas"]
    print(f"  Concepts: {concepts}")
    print(f"  Alphas:   {alphas}")
    n_completions = samples_data["n_completions"]

    # ── Pass 1: keyword scoring (no model needed) ─────────────────────────────
    print("\n── Pass 1: keyword scoring ──")
    kw_scores = {}
    for concept in concepts:
        kw_scores[concept] = {}
        kws = TARGET_KEYWORDS[concept]
        for alpha in alphas:
            comps = samples_data["results"][concept][str(alpha)]
            texts = [c["completion"] for c in comps]
            hit_rate = float(np.mean([keyword_score(t, kws) for t in texts]))
            density  = float(np.mean([keyword_density(t, kws) for t in texts]))
            kw_scores[concept][str(alpha)] = {
                "hit_rate": round(hit_rate, 4),
                "density_per_100w": round(density, 4),
            }
        # Print per concept
        for a in alphas:
            s = kw_scores[concept][str(a)]
            print(f"  {concept:<22} α={a:+.1f}  hit={s['hit_rate']:.3f}  "
                  f"density={s['density_per_100w']:.3f}")

    # ── Pass 2: model-based scoring (PPL) ─────────────────────────────────────
    print(f"\nLoading {MODEL_ID} ...")
    t0 = time.time()
    model, tokenizer = load(MODEL_ID)
    print(f"Loaded in {time.time()-t0:.1f}s")

    llama_model = model.model
    vdata  = json.loads(VECTORS_PATH.read_text())
    s_layers = vdata["target_layers"]  # [8, 16, 24]

    # Pre-convert steering vectors for each concept
    concept_vecs = {}
    for concept in concepts:
        layer_to_vecs = {}
        for li in s_layers:
            vn = np.array(vdata["vectors"][concept][f"layer_{li}"],
                          dtype=np.float32)
            layer_to_vecs[li] = [mx.array(vn)]
        concept_vecs[concept] = layer_to_vecs

    # Warmup: trigger JIT compilation with one forward pass
    print("Warming up JIT compilation ...")
    w_ids = tokenizer.encode("Warmup sentence for JIT compilation.", add_special_tokens=True)
    _ = model(mx.array([w_ids]))
    mx.eval(_)
    print("  Done.")

    # Baseline: alpha=0 (no steering, same for all concepts)
    print("\nComputing baselines (alpha=0) ...")
    t1 = time.time()
    baseline_math_ppl    = compute_perplexity(MATH_PROBES, model, tokenizer)
    baseline_fluency_ppl = compute_perplexity(FLUENCY_SENTENCES, model, tokenizer)
    print(f"  math PPL    = {baseline_math_ppl:.3f}")
    print(f"  fluency PPL = {baseline_fluency_ppl:.3f}")
    print(f"  ({time.time()-t1:.1f}s)")

    ppl_scores = {}
    total = len(concepts) * len(alphas)
    done  = 0
    t_start = time.time()

    for concept in concepts:
        ppl_scores[concept] = {}
        layer_to_vecs = concept_vecs[concept]

        for alpha in alphas:
            if alpha == 0:
                math_ppl    = baseline_math_ppl
                fluency_ppl = baseline_fluency_ppl
            else:
                originals = _patch(llama_model, layer_to_vecs, alpha)
                math_ppl    = compute_perplexity(MATH_PROBES, model, tokenizer)
                fluency_ppl = compute_perplexity(FLUENCY_SENTENCES, model, tokenizer)
                _restore(llama_model, originals)

            ppl_scores[concept][str(alpha)] = {
                "side_effect_ppl": round(math_ppl, 4),
                "side_effect_ratio": round(math_ppl / baseline_math_ppl, 4)
                    if baseline_math_ppl > 0 else None,
                "fluency_ppl": round(fluency_ppl, 4),
                "fluency_ratio": round(fluency_ppl / baseline_fluency_ppl, 4)
                    if baseline_fluency_ppl > 0 else None,
            }
            done += 1
            elapsed = time.time() - t_start
            eta = (elapsed / done) * (total - done) if done > 0 else 0
            print(
                f"  [{done:3d}/{total}]  {concept:<22}  α={alpha:+.1f}"
                f"  math_ppl={math_ppl:.2f}  flu_ppl={fluency_ppl:.2f}"
                f"  ETA {eta:.0f}s"
            )

    # ── Assemble output ───────────────────────────────────────────────────────
    output = {
        "model": MODEL_ID,
        "scoring_date": "2026-07-29",
        "samples_source": str(SAMPLES_PATH.name),
        "description": (
            "target_score.hit_rate: fraction of completions containing ≥1 target keyword; "
            "side_effect_ppl: PPL on math/reasoning probes under steered model; "
            "fluency_ppl: PPL on neutral sentences under steered model"
        ),
        "baselines": {
            "alpha_0_math_ppl": round(baseline_math_ppl, 4),
            "alpha_0_fluency_ppl": round(baseline_fluency_ppl, 4),
        },
        "results": {},
    }

    for concept in concepts:
        output["results"][concept] = {}
        for alpha in alphas:
            a_str = str(alpha)
            kw = kw_scores[concept][a_str]
            pp = ppl_scores[concept][a_str]
            output["results"][concept][a_str] = {
                "alpha": alpha,
                "n_samples": n_completions,
                "keyword_hit_rate": kw["hit_rate"],
                "keyword_density_per_100w": kw["density_per_100w"],
                **pp,
            }

    OUT_PATH.write_text(json.dumps(output, indent=2))
    print(f"\nSaved to {OUT_PATH}  ({OUT_PATH.stat().st_size / 1024:.1f} KB)")


if __name__ == "__main__":
    main()
